# Generated by Django 5.1.4 on 2024-12-14 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetfield',
            name='form_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.formfield'),
        ),
    ]
